package frc.robot;

/**
 * Constants for the Auto-Aim Interpolation Map. THIS FILE IS AUTOMATICALLY GENERATED BY THE
 * REGRESSION TOOL.
 *
 * <p>Data format: {distance, angle, speed} (Speed is 0.0 - 1.0 normalized)
 */
public final class AutoAimConstants {
  public static final double[][] RAW_DATA = {
    {1.00, 10.00, 0.400},
    {3.00, 25.00, 0.700},
    {5.00, 35.00, 0.900}
  };

  private AutoAimConstants() {
    // Utility class
  }
}
